### ISSUE TITLE
Remove `/etc/yum.repos.d/packages.repo` after the installation is finished (successfully or not)

### ISSUE THREAD

**Issue by fidencio** [openshift/kata-operator#10]
Leaving `/etc/yum.repos.d/packages.repo` may cause updates / upgrades to break as rpm-ostree would bail due to the non-existent repository.

**Comment by jensfr** [comment]
I'll work on this. Thanks Fabiano!

**Comment by fidencio** [comment]
@jensfr, another thing I noticed is the rpmdb is in a state where it does believe that packages.repo exists even after being deleted.
So, maybe a cleanup in the db would be needed to ensure it's back to the original state.
